### ISSUE TITLE
Demo不展示菜单栏了

### ISSUE THREAD

**Issue by 1379** [Heeexy/SpringBoot-Shiro-Vue#104]
如下图
![image](https://user-images.githubusercontent.com/34785043/118101577-55609e00-b40a-11eb-882d-af332fe2d4d5.png)

**Comment by 1379** [comment]
不知道作者哪里可以展示吗，我这里网络没有任何问题，浏览器是最新的Chrome

**Comment by Heeexy** [comment]
现在数据恢复了，删角色那里有bug，代码还没修复😂

**Comment by 1379** [comment]
好像还没有恢复吧，我这里还是不显示

**Comment by Heeexy** [comment]
退出重新登录一下

**Comment by Heeexy** [comment]
代码更新了下，避免被人修改管理员信息了🤣
