### ISSUE TITLE
这个项目逻辑有问题啊！！！

### ISSUE THREAD

**Issue by gliiii** [Heeexy/SpringBoot-Shiro-Vue#106]
配置新用户，之后分配用户角色为非管理员，文章菜单不能做修改和新增。结果登陆进去所有菜单都没有了。看了代码，只有管理员才能查询菜单跟权限。不好用！
![image](https://user-images.githubusercontent.com/47062805/119753228-f81c2080-bed0-11eb-909c-69f514743fef.png)
![image](https://user-images.githubusercontent.com/47062805/119753282-108c3b00-bed1-11eb-83c2-fc307c3c1215.png)
![image](https://user-images.githubusercontent.com/47062805/119753267-0bc78700-bed1-11eb-923a-d7e269067c0b.png)
这里整个菜单都没有。
![image](https://user-images.githubusercontent.com/47062805/119753330-2c8fdc80-bed1-11eb-97ae-9e994dc735ab.png)

**Comment by Heeexy** [comment]
感谢反馈！
最近升级一版，没好好测试，十分惭愧。
现已修复
