### ISSUE TITLE
是否有更优的方案了？

### ISSUE THREAD

**Issue by sexyflaw** [Heeexy/SpringBoot-Shiro-Vue#109]
前端本地尝试启动，因版本过老报错了。我了解的权限管理可以使用shiro和spring security,还有写缓存拦截的，这三种方案哪个比较灵活，能充分满足业务需求呢。本项目的解决方案是否还可以使用，是否存在更优的方案。网上查了资料，没有深入了解那两个框架，我个人倾向写缓存拦截，各位有什么建议想法

**Comment by Heeexy** [comment]
用能满足需求的最简单的方案。自己的业务需求只有自己评估了
