### ISSUE TITLE
开发工具

### ISSUE THREAD

**Issue by LadyTeng** [Heeexy/SpringBoot-Shiro-Vue#11]
请问使用什么开发工具 和 开发环境 ,希望有时间帮忙解答

**Comment by Heeexy** [comment]
Intellij IDEA 前后端都好用.

**Comment by LadyTeng** [comment]
是需要下载关于vue的插件么?项目down下来发现那堆js在报错,是不是关于vue的问题,idea是不是要下载什么插件之类的

**Comment by Heeexy** [comment]
嗯  有vue和nodejs的插件   下载了插件就不会提示报错了

**Comment by LadyTeng** [comment]
方便说下这两个插件的名字么?我这面找到一个vue.js这个鬼,但是在市场下载不下来,是不是我找错了

**Comment by Heeexy** [comment]
是那个没错   37W下载量的    是网速慢么   为什么下载不下来

**Comment by LadyTeng** [comment]
我在研究下,谢谢

**Comment by Heeexy** [comment]
https://github.com/judasn/IntelliJ-IDEA-Tutorial     这个教程好  Intellij非常值得花时间学

**Comment by LadyTeng** [comment]
多谢
