### ISSUE TITLE
角色删除后，用户仍旧显示拥有被删除的角色

### ISSUE THREAD

**Issue by youdengtuzi** [Heeexy/SpringBoot-Shiro-Vue#110]
1.新建一个角色ROLEA
2.新建一个用户USERA，增加新建角色权限USERA-ROLEA
3.删除角色ROLEA
4.用户USERA权限仍旧显示拥有ROLEA

**Comment by Heeexy** [comment]
的确真实环境需要关联删除，
并且此时还有可能导致用户0个角色，用户登录的时候还要判断是否至少拥有1个角色，引导申请权限...

demo里就没做这么详细了哈
