### ISSUE TITLE
项目缺少依赖

### ISSUE THREAD

**Issue by geeker1234** [Heeexy/SpringBoot-Shiro-Vue#111]
缺少mybatis依赖；

提几个建议：
1.mybatis可以升级为mybatis plus
2.目前的用户密码也没加密，直接明文存储的
3.权限菜单列表及配置可以出一下，就不用手动插入sql了

**Comment by Heeexy** [comment]
本项目很多地方处理得非常粗糙原始，因为只打算做个demo，分享下权限设计思路，具体实践还是靠各位自己哈

**Comment by geeker1234** [comment]
好的 自己动手丰衣足食
