### ISSUE TITLE
登出是怎么清除动态添加的路由信息的，没有找到对应的代码

### ISSUE THREAD

**Issue by WangFeng-WF** [Heeexy/SpringBoot-Shiro-Vue#112]
求助，登录的时候根据角色通过addRoutes动态添加了路由，登出的时候怎么清除掉这些动态添加的路由的呢？

**Comment by Heeexy** [comment]
搜一下下面的代码， SET_ROUTERS 可以修改路由，有需要可以用这个方法清除下

```
        //执行设置路由的方法
        commit('SET_ROUTERS', accessedRouters)
```

**Comment by WangFeng-WF** [comment]
> 搜一下下面的代码，SET_ROUTERS可以修改路由这个，有需要可以用的方法清除下
> 
> ```
>         //执行设置路由的方法
>         commit('SET_ROUTERS', accessedRouters)
> ```

嗯嗯，这里是设置用户的路由到getters里面去的对吧，组中添加到vue实例是这行代码吧

**Comment by WangFeng-WF** [comment]
> > 搜一下下面的代码，SET_ROUTERS可以修改路由这个，有需要可以用的方法清除下
> > ```
> >         //执行设置路由的方法
> >         commit('SET_ROUTERS', accessedRouters)
> > ```
> 
> 嗯嗯，这里是设置用户的插入到getters里面去的对吧，组中添加到vue实例是这行代码吧

//生成该用户的新路由json操作完毕之后,调用vue-router的动态新增路由方法,将新路由添加
router.addRoutes(store.getters.addRouters);

**Comment by WangFeng-WF** [comment]
> > > 搜一下下面的代码，SET_ROUTERS可以修改路由这个，有需要可以用的方法清除下
> > > ```
> > >         //执行设置路由的方法
> > >         commit('SET_ROUTERS', accessedRouters)
> > > ```
> > 
> > 
> > 嗯嗯，这里是设置用户的插入到getters里面去的对吧，组中添加到vue实例是这行代码吧
> 
> //生成该用户的新路由json操作完成后，调用vue-router的动态添加方法，将新路由添加
> router.addRoutes(store.getters.addRouters);
这里有一个add的动作，但是退出登录，我没找到router有delete的一个动作。

**Comment by Heeexy** [comment]
退出登录的时候我没写，搞demo的时候没发现问题就没处理这个了

**Comment by WangFeng-WF** [comment]
> 退出登录的时候我没写，搞demo的时候没发现问题就没处理这个了

嗯嗯，多谢啦，我自己再研究研究。
