### ISSUE TITLE
用户表中不应该有role_id

### ISSUE THREAD

**Issue by h2285409** [Heeexy/SpringBoot-Shiro-Vue#113]
用户和角色应该是一对多不是多对多的关系， UserMapper.xml 161行 
LEFT JOIN sys_user u ON r.id = u.role_id AND u.delete_status = '1' 建议改为
LEFT JOIN sys_user_role ur ON r.id = ur.role_id AND ur.delete_status = '1'

**Comment by Heeexy** [comment]
是的，上次改成支持多角色的时候没改干净，多谢反馈
