### ISSUE TITLE
请问去除shiro后权限管理这一块是怎么完成的？

### ISSUE THREAD

**Issue by SuMinghua** [Heeexy/SpringBoot-Shiro-Vue#114]
您好！请问去除shiro后，权限管理这一块是怎么完成的？能麻烦您指点一下吗？谢谢！

**Comment by Heeexy** [comment]
用了自定义的注解 https://github.com/Heeexy/SpringBoot-Shiro-Vue/blob/master/back/src/main/java/com/heeexy/example/config/annotation/RequiresPermissions.java

配合自定义的拦截器 https://github.com/Heeexy/SpringBoot-Shiro-Vue/tree/master/back/src/main/java/com/heeexy/example/config/filter/PermissionAspect.java
