### ISSUE TITLE
前端使用npm install 出现gyp verb `which` failed Error: not found: python2

### ISSUE THREAD

**Issue by conciseL** [Heeexy/SpringBoot-Shiro-Vue#116]
我已经尝试卸载原有的python3,安装了python2,但还是提示gyp verb `which` failed Error: not found: python2
是否有人知道如何解决呢，感激不尽

**Comment by conciseL** [comment]
已经解决了，将node版本降低至6.16.0就成功解决了

**Comment by includeno** [comment]
我也遇到了同样的问题，感谢

**Comment by includeno** [comment]
由于M1 Mac不支持老版本NodeJS，我放弃了
