### ISSUE TITLE
前后端如何在IDEA部署的呢

### ISSUE THREAD

**Issue by Nick6699** [Heeexy/SpringBoot-Shiro-Vue#12]
你好，我把整个项目下载下来了
请问一下，如何在idea里面运行起来呢

**Comment by Heeexy** [comment]
前后端分开部署的,是两个独立项目

后端:idea导入back文件夹.  运行MyApplication 的main方法就可以了

前端:如果不使用idea的话, 在 vue 文件夹下面命令行运行  npm install ,   等安装完毕再npm run dev. 
最好是先简单学习下nodejs和webpack工具

**Comment by Nick6699** [comment]
请问一下前端和后端怎么联系起来的

例：查看用户列表  UserController 里面的 /list请求，
我查到提交的是CommonUtil 里面的successPage里面的result数据
这个result是如何放入前端的?
或者说前端的  user/请求 怎么到后端拿数据的？
一直没有想明白这个问题

**Comment by Heeexy** [comment]
这个 /list 接口是可以直接访问的,   比如   http://localhost:8080/list   你可以浏览器打开看下返回的json

前端就是通过nodejs服务器请求了这个接口

**Comment by heyha** [comment]
> 你好，我把整个项目下载下来了
> 请问一下，如何在idea里面运行起来呢

请问idea要做什么配置吗？安装node.js和vue插件之后直接导入back文件夹吗？

**Comment by Heeexy** [comment]
> > 你好，我把整个项目下载下来了
> > 请问一下，如何在idea里面运行起来呢
> 
> 请问idea要做什么配置吗？安装node.js和vue插件之后直接导入back文件夹吗？

back文件夹是后端项目，不需要装插件，直接Open作为一个spring项目。
vue文件夹是前端项目，另外Open作为一个项目。要安装node.js和vue插件的

**Comment by heyha** [comment]
> > > 你好，我把整个项目下载下来了
> > > 请问一下，如何在idea里面运行起来呢
> > 
> > 
> > 请问idea要做什么配置吗？安装node.js和vue插件之后直接导入back文件夹吗？
> 
> back文件夹是后端项目，不需要装插件，直接Open作为一个spring项目。
> vue文件夹是前端项目，另外Open作为一个项目。要安装node.js和vue插件的

![image](https://user-images.githubusercontent.com/33803259/49502637-71160080-f8b0-11e8-85a4-8123ec673d7a.png)
请问这个是什么问题？

**Comment by Heeexy** [comment]
看看后端debug日志里sql执行的情况吧

**Comment by heyha** [comment]
> 看看后端debug日志里sql执行的情况吧

![image](https://user-images.githubusercontent.com/33803259/49507851-5053a800-f8bc-11e8-8df0-cb8a6e2a2999.png)
应该是数据库没有连接成功。请问后端的项目打开之后 需要进行数据库连接或者配置吗？

**Comment by Heeexy** [comment]
需要的   application.yml里有mysql的配置  你看下
