### ISSUE TITLE
你好，有给后端传JSON数组的写法吗？

### ISSUE THREAD

**Issue by C01day** [Heeexy/SpringBoot-Shiro-Vue#120]
好像传的都是单个JSON

**Comment by Heeexy** [comment]
https://zhuanlan.zhihu.com/p/89223401    看看这篇文章里有没有你需要的

**Comment by C01day** [comment]
好的多谢，还想请问一下，为什么有些接收参数用的是`HttpServletRequest request`，有的是`@RequestBody JSONObject requestJson`，第一次用不太懂，想请教一下，谢谢

**Comment by Heeexy** [comment]
没有什么讲究的，是我写简单的crud就偷懒都用 JSONObject。
 get请求也把url里的参数通过 CommonUtil.request2Json(request) 转成了JSONObject

这项目只是想展示权限设计的思路，不要把项目里的代码当成规范的哈
