### ISSUE TITLE
后端运行时间过长，  为什么页面一直在加载

### ISSUE THREAD

**Issue by 15638817940** [Heeexy/SpringBoot-Shiro-Vue#121]
打了debug  后端运行时间过长的话，  为什么页面一直打转转啊？这个页面要怎么调试啊
![image](https://user-images.githubusercontent.com/72065297/231323265-cada96e6-74d7-4123-9aca-762753a18ccd.png)

**Comment by Heeexy** [comment]
没有看明白，后端打了断点，接口没返回数据，前端表格可不就是loading状态么

**Comment by 15638817940** [comment]
好的 问题已经解决
