### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by 15638817940** [Heeexy/SpringBoot-Shiro-Vue#122]
我想问个问题，需要放到到服务器上，是不是要先把vue 打包 放到 public 文件夹下，然后在把springboot打成jia包。丢到服务器上。你看一下我这个前段配置 这里对不对。
![企业微信截图_1683265977967](https://user-images.githubusercontent.com/72065297/236386775-320064ea-649f-4113-9ac4-bafea0bc87e6.png)
那丢到服务器上访问的话  是不是通过 http://192.168.3.xxx:8066/   这么访问啊？

**Comment by GYFgaoyuefei** [comment]
好的，我已收到

**Comment by 15638817940** [comment]
![企业微信截图_16832660518211](https://user-images.githubusercontent.com/72065297/236387098-26c4cfc0-bace-4675-be26-b0d4b3616ec1.png)
![企业微信截图_16832660854842](https://user-images.githubusercontent.com/72065297/236387109-ebf12a10-a409-484a-9750-0d15433f4470.png)
我打本地的包是没问题的 可以通过127.0.0.1:8066访问， 我问题下放到服务器上是不是 也是 http://192.168.3.xxx:8066/ 这样访问的

**Comment by Heeexy** [comment]
BASE_URL 这个参数是axios请求后端用到的。

部署到服务器上你就看你请求后端接口用啥地址。  你用 http://192.168.3.xxx:8066/ 是遇到什么报错了么


```
const service = axios.create({
  baseURL: process.env.BASE_URL, // api的base_url
  timeout: 15000                  // 请求超时时间
})
```

**Comment by 15638817940** [comment]
还没部署我就不确定 部署的话这个base_url 这么写对不对，因为我在本地就是 base_url 这么写的  127.0.0.1:8066

**Comment by 15638817940** [comment]
加入我在  192.168.xxx 这个服务器上部署   base_url 要怎么写，  配置文件里需要写服务器的ip嘛？

**Comment by Heeexy** [comment]
最好用 "/"  ， 如果项目挂在域名下有path前缀， 那就 "/前缀" 

让浏览器去自动给你补全前面的协议、域名、端口。

**Comment by 15638817940** [comment]
BASE_URL  直接 一个/  就可以是吧？配置文件里不需要写  服务器ip 啥的嘛？

**Comment by Heeexy** [comment]
尽量别写，写了就定死了只能部署在这个ip上了。  换服务器部署你还得改配置重新打包

**Comment by 15638817940** [comment]
好的 谢谢，我试试  
![image](https://user-images.githubusercontent.com/72065297/236396883-38a7ae6d-1380-4174-b18b-06baceca4e6d.png)
还有如果前段开启这个 mode: 'history'   我请求的时候 一次没问题 后面他请求的时候就多加了路径， 404， 这个要怎么处理啊。

**Comment by Heeexy** [comment]
前端的我也不熟，还是自己去查下哈

**Comment by 15638817940** [comment]
好的好的  谢谢了
