### ISSUE TITLE
有多租户实现的思路吗？

### ISSUE THREAD

**Issue by Derrick-xn** [Heeexy/SpringBoot-Shiro-Vue#132]
我想在这个项目的基础上加一套多租户的概念逻辑，但是想法比较乱，不太成熟，有什么好的建议吗？

**Comment by Heeexy** [comment]
前端：登录到系统后做2件事
1. 查询有权限的租户列表，供用户选择
2. 选完之后，每个请求都带上租户id

后端：
1. 增加一个数据权限拦截器，校验用户是否有这个租户id的权限

数据库
1. 角色表、用户-角色关联标增加一个字段， 租户id，实现用户在各个租户下有不同的角色
