### ISSUE TITLE
项目拉下来，启动了，本地访问URL是什么，vue 没在back项目里，怎么页面跳转啊。。

### ISSUE THREAD

**Issue by 475132489** [Heeexy/SpringBoot-Shiro-Vue#14]

**Comment by Heeexy** [comment]
vue 项目单独启动的.
在vue文件夹下执行 npm run install   
然后 npm run dev

**Comment by 475132489** [comment]
ok ,跑起来了，第一次用vue ~     vue 可以像html 这样在项目里当做页面跳转显示，不单独启动吗？

**Comment by Heeexy** [comment]
npm run build 打包成静态文件之后可以把生成的 dist目录下的内容放到springboot的静态文件夹public下面
然后springboot配置个 首页路径就可以访问了.

不过平时调试的时候, 还是分开启动比较好.

**Comment by ZeroYip** [comment]
请问该项目token的生成依靠的是什么？（没有JWT或者相关的工具）

**Comment by Heeexy** [comment]
暂时没有用到token，直接用的session

**Comment by ZeroYip** [comment]
那请问这样的话，前后端分离（跨域访问）的情况下，前端的Ajax请求应该怎么填写（网上的教程一般都说加上token），后端如何认证该用户？谢谢~

**Comment by Heeexy** [comment]
很久没研究这个了，貌似用token放header中带着是最方便的，就没有跨域的问题了。
至于token是用jwt还是什么随机值，都可以自己定，看怎么方便怎么来。
jwt已经有完善的加密和认证方案了，当然是首选。
如果要自己生成随机值token的话，就还得考虑token的储存，获取等等问题

**Comment by Heeexy** [comment]
我这个因为部署是打包到一起部署的，所以用session就比较直接。
当然用JWT的话肯定更好哈

**Comment by ZeroYip** [comment]
好，我尝试一下，谢谢！

**Comment by ZeroYip** [comment]
请问你所说打包倒一起部署，指的是他们共用一个端口吗？

**Comment by Heeexy** [comment]
是直接把前端文件打包放到SpringBoot项目中
npm run build 打包成静态文件之后可以把生成的 dist目录下的内容放到springboot的静态文件夹public下面

**Comment by ZeroYip** [comment]
没有，我的意思是，前端是如何保持登录状态的（是因为前后端共用一个端口，所以可以使用同一个session吗）？
