### ISSUE TITLE
请问关于session的时间设置在哪儿呢？  谢谢了！

### ISSUE THREAD

**Issue by xzgilhm** [Heeexy/SpringBoot-Shiro-Vue#15]
想知道一下关于session的设置  谢谢！！

**Comment by Heeexy** [comment]
我也没设置过，不过你可以搜下springboot设置session和Shiro管理session的文章
比如 https://blog.csdn.net/qq_31971675/article/details/52081742

**Comment by xzgilhm** [comment]
非常感谢！
