### ISSUE TITLE
项目使用IDEA导入后，在启动类里无法启动，是什么原因哪？

### ISSUE THREAD

**Issue by zk750430** [Heeexy/SpringBoot-Shiro-Vue#18]
![1](https://user-images.githubusercontent.com/28125931/40877996-cb7d26e2-66bc-11e8-80c1-1118c73d479f.png)

**Comment by Heeexy** [comment]
back文件夹和vue文件夹要分成两个项目导入

**Comment by zk750430** [comment]
back启动了，vue启动报错 Cannot find module 'node-sass'

**Comment by zk750430** [comment]
解决了，辛苦大佬了
