### ISSUE TITLE
通过案例后台整合shiro出现了问题

### ISSUE THREAD

**Issue by carrymumu** [Heeexy/SpringBoot-Shiro-Vue#19]
我通过postman测试了登录后，doGetAuthorizationInfo方法一直不执行。并且无论controller上的方法有没有配置需要权限的注释，都无法执行，都直接会提醒我在AjaxPermissionsAuthorizationFilter配置的报错登录已过期，难道是因为无法通过postman进行登录状态的保持么？希望能帮帮我。

**Comment by carrymumu** [comment]
在我通过pc端下载的postman测试的时候终于成功了，卡了两天栽在了浏览器上下载的postman插件上了

**Comment by Heeexy** [comment]
postman没有把登录状态带着, 
以前用postman插件需要再加一个额外的插件获取chrome的web登录状态. 
现在都是用PC版的了吧, 不太清楚了

**Comment by carrymumu** [comment]
对，我一直以为是自己代码没配置好，所以导致登录的时候没有授权。后来才发现登录的时候本来就不需要授权，只有通过url访问了加了需要权限注释的才会开始确认是否有权限。最后才发现是插件的原因，不懂底层，直接用就容易出现这种奇奇怪怪的bug。
