### ISSUE TITLE
关于shiro

### ISSUE THREAD

**Issue by Lovnx** [Heeexy/SpringBoot-Shiro-Vue#20]
1、项目登录加密貌似有点问题。
2、建议整合redis，将shiro session放置在redis，解决单点问题。

**Comment by Heeexy** [comment]
我的实际项目也是用redis的 , 因为这个项目只是计划介绍权限设计思路 , 所以尽量做简单一点了

**Comment by Lovnx** [comment]
我在整合扩展的时候遇到蛮多问题，可否参考一下这部分代码？谢谢

**Comment by Heeexy** [comment]
jwt可以解决登录的问题么,那个我还没研究过
redis的话我项目中也只是简单缓存指定userid的权限信息  可能满足不了你的需求哈

**Comment by Lovnx** [comment]
好的
