### ISSUE TITLE
关于登录的问题

### ISSUE THREAD

**Issue by 460332339** [Heeexy/SpringBoot-Shiro-Vue#21]
你好，我按照你的项目做了个demo，登录方法的代码是：
Subject currentUser = SecurityUtils.getSubject();
UsernamePasswordToken token = new UsernamePasswordToken(username, password);
currentUser.login(token);
但是登录的时候断点没有进到这里面，而是执行了Realm中的doGetAuthenticationInfo方法，这正常吗？
还有，如果我登录时候也需要输入昵称来校验，应该怎么实现呢？

**Comment by Heeexy** [comment]
config/shiro/ShiroConfiguration.java  配置了不需要拦截的地址,你可能是需要把你的登录方法加到这里面,
或者通过debug看一下是从哪里跳进的这个doGetAuthenticationInfo方法

 自定义登录校验的话,可以自己实现一个AuthenticationToken接口,然后修改下UserRealm 里的doGetAuthenticationInfo业务逻辑
