### ISSUE TITLE
路由还是写死在代码中 没有实现真正的动态

### ISSUE THREAD

**Issue by hanzhenchaoGit** [Heeexy/SpringBoot-Shiro-Vue#22]
路由可否从后端获取 然后动态添加呢 我之前的做法跟你的是一样的  后来想做成后端获取的 出问题了 有兴趣你 也可以试一下

**Comment by Heeexy** [comment]
的确目前的全部路由是写死在前端代码里的,登录用户的路由是后端传过来的,
是import遇到问题了么, 我对前端很久也没研究了,未必能解决哈

**Comment by hanzhenchaoGit** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    哈哈 我现在也没法定位到问题  不可描述  很纠结 所以在四处找示例  看是哪个地方出问题了 


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                


    在2018年6月26日 15:01，Heeexy<notifications@github.com> 写道： 


的确目前的全部路由是写死在前端代码里的,登录用户的路由是后端传过来的,
是import遇到问题了么, 我对前端很久也没研究了,未必能解决哈
