### ISSUE TITLE
bug,邮件已发送

### ISSUE THREAD

**Issue by RMzcq** [Heeexy/SpringBoot-Shiro-Vue#23]
heeexy:   
    你好，自己这边在学习vue，并搭建框架，使用您的代码的时候发现了一个bug，修改用户的菜单栏目权限，但是菜单照常显示，发现代码漏掉了一行判断菜单有效的代码，代码如下：
![331b4dd6-28d1-4c5c-89dc-ed234f438c9d](https://user-images.githubusercontent.com/7501342/42071874-4ef482d0-7b90-11e8-9948-0e2b0cb9b243.png)

加上之后就ok了。

**Comment by Heeexy** [comment]
的确存在这个问题,多谢指出,马上进行修复

**Comment by RMzcq** [comment]
这样还会导致admin登录不了，所以这一块判断得改一下，你可以验证一下，我没严谨的验证admin用户

**Comment by Heeexy** [comment]
这个demo里面     admin账户我设置的是搜全部权限   没走这个sql啊

**Comment by RMzcq** [comment]
JSONObject userPermission = permissionDao.getUserPermission(username);
这个查询出来会为null。

**Comment by Heeexy** [comment]
那是没数据了吧

**Comment by Heeexy** [comment]
明白了,马上改哈
