### ISSUE TITLE
请问作者是如何解决跨域问题的

### ISSUE THREAD

**Issue by PiedPiperr** [Heeexy/SpringBoot-Shiro-Vue#24]
我也下载了一个 vue-admin，然后请求作者你的后端登陆接口，存在跨域问题。你的后端代码好像也没配置跨域的方法。
你的demo是不是发布在ngix里的？
![image](https://user-images.githubusercontent.com/32378929/42088736-34153c42-7bcd-11e8-9d2a-3fc5e3392b07.png)

**Comment by Heeexy** [comment]
## 开发环境
// 1. axios的baseURL设置为/api
// 2. 如下设置
proxyTable: {
      '/api': {
        target: 'http://127.0.0.1:8080/',
        changeOrigin: true,
        pathRewrite: {
          '^/api': '/'
        }
      }
    },

## 发布demo
npm run build 
把dist目录下的静态文件扔到springboot的public文件夹下，配置下首页指向 “public/index.html”
springboot项目打jar包   
linux服务器上执行java -jar ...命令就可以了

跨域我就没有再去研究了，如果要解决的话你再搜一下别人的方案吧
