### ISSUE TITLE
登录接口一直返回“登陆已过期,请重新登陆”

### ISSUE THREAD

**Issue by RaulSteven** [Heeexy/SpringBoot-Shiro-Vue#27]
无论是通过postman，还是nodejs的网页发起请求，都返回如下：

{
    "returnCode": "20011",
    "returnMsg": "登陆已过期,请重新登陆"
}

**Comment by yp199618** [comment]
经过测试，打成jar包确实会一直报“登陆已过期,请重新登陆”错误，打成war包部署到tomcat底下就可以正常访问api了
打war包参考链接:[点我打war包](https://blog.csdn.net/liyongbing1122/article/details/79204026)

**Comment by Heeexy** [comment]
> 经过测试，打成jar包确实会一直报“登陆已过期,请重新登陆”错误，打成war包部署到tomcat底下就可以正常访问api了
> 打war包参考链接:[点我打war包](https://blog.csdn.net/liyongbing1122/article/details/79204026)

示例网站就是打jar包的，是不是修改了什么配置，是通过什么访问api的呢

**Comment by yp199618** [comment]
只改动了数据库用户名密码，其他配置没有改，直接运行的jar文件。用的postman windows客户端，
建议：重新下载源码，重新打jar运行试试，和可能是代码问题，因为不止我自己遇到了报“登陆已过期,请重新登陆”错误这个问题

**Comment by marvin-min** [comment]
这个问题解决了没有啊？

**Comment by dlsyaim** [comment]
npm run build打包，放在publish目录下运行，一直提示登录已过期，请重新登录！
