### ISSUE TITLE
权限管理，加载列表成功，修改时返回错误。

### ISSUE THREAD

**Issue by RaulSteven** [Heeexy/SpringBoot-Shiro-Vue#28]
![tim 20180713153039](https://user-images.githubusercontent.com/22462473/42678588-ea1b88ae-86b1-11e8-9759-7f216f61d5ab.png)
![tim 20180713153052](https://user-images.githubusercontent.com/22462473/42678591-eb48b3dc-86b1-11e8-821d-6fee5fd991ad.png)
![tim 20180713153134](https://user-images.githubusercontent.com/22462473/42678593-eba917ae-86b1-11e8-88ac-613d71c31d67.png)

**Comment by Heeexy** [comment]
在后端debug看sessionid呢

**Comment by RaulSteven** [comment]
是跨域问题没解决，用您之前的proxyTable没问题
