### ISSUE TITLE
项目存在bug,权限控制不完全

### ISSUE THREAD

**Issue by landuo** [Heeexy/SpringBoot-Shiro-Vue#29]
您好，我在测试时发现，当某角色仅拥有某种权限时，实际上已经拥有了全部权限。 比如分配了角色管理中的修改时，实际上是可以新增和删除的。我是在你那个线上测试的，还没Git到本地测试。

**Comment by Heeexy** [comment]
debug看看UserRealm的doGetAuthorizationInfo查询出来的权限包括哪些呢
