### ISSUE TITLE
跨域要怎么处理？

### ISSUE THREAD

**Issue by cliff01** [Heeexy/SpringBoot-Shiro-Vue#3]
咨询一下，不采用代理的方式实现，添加跨域拦截后，默认都跳转到AjaxPermissionsAuthorizationFilter的onAccessDenied方法里面，前面的异常怎么跟踪？

**Comment by Heeexy** [comment]
不使用代理的话,每次sessionId都会变.
配置好像麻烦一点,  我印象里大概是

axios要 withCredentials: true

后端要配置个类允许跨域
```
@Configuration
public class CorsConfig {
    private CorsConfiguration buildConfig() {
        CorsConfiguration corsConfiguration = new CorsConfiguration();
        corsConfiguration.addAllowedOrigin("*"); // 1 设置访问源地址
        corsConfiguration.addAllowedHeader("*"); // 2 设置访问源请求头
        corsConfiguration.addAllowedMethod("*"); // 3 设置访问源请求方法
        corsConfiguration.setAllowCredentials(true);
        return corsConfiguration;
    }
    @Bean
    public CorsFilter corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        source.registerCorsConfiguration("/**", buildConfig()); // 4 对接口配置跨域设置
        return new CorsFilter(source);
    }
}
```

**Comment by Heeexy** [comment]
corsConfiguration貌似还要指定允许请求的ip才行,记得不是很清楚了.

**Comment by cliff01** [comment]
谢谢，next('/login')里面怎么设withCredentials？

**Comment by Heeexy** [comment]
在 src/utils/api.js 
const service = axios.create({
  baseURL: process.env.BASE_URL, // api的base_url
  timeout: 15000,                  // 请求超时时间
  withCredentials: true
})

**Comment by cliff01** [comment]
访问没问题了，登录就是一直报登陆已过期,请重新登陆

**Comment by Heeexy** [comment]
这还是因为 sessionId 每次都变了.
Session session = SecurityUtils.getSubject().getSession(); 可以获取到session信息,证明这一点.
withCredentials: true 和 CorsConfig.java 配置好的话不会这样.
不好意思这个确实不记得这个怎么配了.

最好的解决方法应该还是服务器端不生成会话session，而是每次请求时带上用户身份进行认证。
http://jinnianshilongnian.iteye.com/blog/2041909

这需要前后端都改造一下，我也暂时还没有研究。。

**Comment by cliff01** [comment]
response.setHeader("Access-Control-Allow-Credentials","true"); //是否支持cookie跨域
加上这个就可以登录了

**Comment by Heeexy** [comment]
奥 ，加个过滤器就好了么

**Comment by cliff01** [comment]
是的，开始加了可能是没生效，刚刚又试的时候又可以了。而且开始Origin，Header里面用统配符*，报一个不允许使用，改成制定的才可以，现在去掉测试也没问题了。不知道是不是引用在父工程的影响。明天在看看。

**Comment by 344310362** [comment]
你2个项目是怎么部署到一起的

**Comment by Heeexy** [comment]
一种是分开部署，需要自己处理跨域问题
另一种是把前端 npm run build打包之后 把静态文件扔到springboot项目里的public文件夹下面

**Comment by 344310362** [comment]
跨域的问题我解决了：
- vue 里面要改革地方:  src/utils/api.js
```
// 创建axios实例
const service = axios.create({
  baseURL: process.env.BASE_URL, // api的base_url
  timeout: 15000,                  // 请求超时时间2
  withCredentials: true        //【这里要添加下这个】
})
```
- java后端添加个过滤器
```
@Configuration
public class JxWebMvcConfiguration extends WebMvcConfigurerAdapter {
    @Bean
    public FilterRegistrationBean corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("*");
        config.addAllowedHeader("*");
        config.addAllowedMethod("*");
        source.registerCorsConfiguration("/**", config);
        FilterRegistrationBean bean = new FilterRegistrationBean(new CorsFilter(source));
        bean.setOrder(0);
        return bean;
    }
}
```
