### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by chengwengao** [Heeexy/SpringBoot-Shiro-Vue#30]
npm install正常，运行npm run dev时报错
![image](https://user-images.githubusercontent.com/25266894/42914979-d5f380b6-8b2f-11e8-8553-fe68a260aa7f.png)
根据提示执行`npm install --save svg-baker-runtime/browser-symbol`命令，报错，错误日志：
![image](https://user-images.githubusercontent.com/25266894/42915045-1a0db50a-8b30-11e8-8d02-168110a8ee91.png)
请问如何解决？

**Comment by Heeexy** [comment]
执行一下第一张图片的最下面一行

如果这种问题多的话    
 npm     
cnpm  
  npm --registry=https://registry.npm.taobao.org
都试试

**Comment by chengwengao** [comment]
都试过了，还是不行，是不是git仓库变了？
![image](https://user-images.githubusercontent.com/25266894/42916737-2d0439dc-8b39-11e8-9b24-70cedaff6e1c.png)

**Comment by Heeexy** [comment]
把node_modules文件夹删了  重新  cnpm呢       
cnpm就不需要加--registry了

**Comment by chengwengao** [comment]
把node_modules文件夹删除后重新执行cnpm install就可以了，谢谢！

**Comment by yxf781225** [comment]
browser-symbol

**Comment by yxf781225** [comment]
browser-symbol 404错误了

**Comment by Heeexy** [comment]
> browser-symbol 404错误了

browser-symbol 是啥
