### ISSUE TITLE
用户权限菜单下的用户列表页面BUG

### ISSUE THREAD

**Issue by superZhouDaLu** [Heeexy/SpringBoot-Shiro-Vue#31]
#### 用户列表页面随意选择一条进行编辑，然后选择关闭dialog窗口，点击添加，就会出现被编辑的数据内容缺失的bug。原因：user.vue页面showUpdate的方法中 this.tempUser = this.list[$index] ，但是 showCreate方法又将tempUser 的值全部赋值为空 ，导致列表中之前被编辑的数据展示异常。

**Comment by Heeexy** [comment]
感谢告知,已修复
