### ISSUE TITLE
跨域

### ISSUE THREAD

**Issue by syf1211** [Heeexy/SpringBoot-Shiro-Vue#32]
您好，我想请教一下，对于本地跨域，和上线时跨域，分别怎么解决？

**Comment by Heeexy** [comment]
本地node配置 proxyTable就可以了
上线后前后端不分离的话可以把前端打包, 直接放到后端静态文件夹.
分离的话方法我也不熟   你再搜下哈

http://heeexy.com/2017/10/22/build-springboot-shiro-vue/
