### ISSUE TITLE
怎么实现部署呢

### ISSUE THREAD

**Issue by benyVip** [Heeexy/SpringBoot-Shiro-Vue#33]
看到前后端的代码是分离的，怎么部署呢？

**Comment by Heeexy** [comment]
前端打包之后就是纯静态文件,随便部署在Nginx还是什么服务器里

**Comment by benyVip** [comment]
那就是前后端分开部署是么？

**Comment by Heeexy** [comment]
可以的.
不会玩Nginx的话,前端打包扔到springboot的静态文件夹里也是可以一起部署

**Comment by benyVip** [comment]
好的，我试试看，他他们仍在一起，然后启动一个spring的进程是么




发自网易邮箱大师


在2018年08月15日 22:47，Heeexy<notifications@github.com> 写道：

可以的.
不会玩Nginx的话,前端打包扔到springboot的静态文件夹里也是可以一起部署

**Comment by Heeexy** [comment]
是的, 打包扔到springboot 的resource/public文件夹下就可以了

DefaultView.java里已经配置过了首页路径指向index.html了

**Comment by benyVip** [comment]
我试过了，应该不是配置在public这个目录下




发自网易邮箱大师


在2018年08月15日 22:56，Heeexy<notifications@github.com> 写道：

是的, 打包扔到springboot 的resource/public文件夹下就可以了

DefaultView.java里已经配置过了首页路径指向index.html了

**Comment by Heeexy** [comment]
![Uploading image.png…]()

**Comment by benyVip** [comment]
我的文件的配置也毛病呀


发自网易邮箱大师


在2018年08月16日 09:15，Heeexy<notifications@github.com> 写道：

**Comment by Heeexy** [comment]
那只能你再检查下 或者找找其它放静态文件路径的方法啦

**Comment by benyVip** [comment]
可能build的时候生成的文件不对吧




发自网易邮箱大师


在2018年08月16日 22:06，Heeexy<notifications@github.com> 写道：

那只能你再检查下 或者找找其它放静态文件路径的方法啦

**Comment by Heeexy** [comment]
生成的dist下的文件扔进来   不包括dist
或者你直接去public下面自己建个index.html   看看localhost:8080/   是不是进了你的index.html

**Comment by benyVip** [comment]
可以的，那就是打包的问题的了，打包的时候没有把对应的一些index的页面打进去呀，你的打包命令是什么呀




发自网易邮箱大师


在2018年08月16日 22:12，Heeexy<notifications@github.com> 写道：

生成的dist下的文件扔进来 不包括dist
或者你直接去public下面自己建个index.html 看看localhost:8080/ 是不是进了你的index.html

**Comment by Heeexy** [comment]
之前npm install 过没有

**Comment by benyVip** [comment]
install 过的来，我就发现跟我在公司玩的不一样，npm run install ，出现一个模块的安装呀，这个我知道的




发自网易邮箱大师


在2018年08月16日 22:47，Heeexy<notifications@github.com> 写道：

之前npm install 过没有
