### ISSUE TITLE
布署到服务器上后

### ISSUE THREAD

**Issue by ywb21201** [Heeexy/SpringBoot-Shiro-Vue#36]
您好！
我将您的工程在本地上跑没有问题，放到远程服务器上后请求getInfo时，总是被shiro返回登录过期
err_code: 20011
err_msg: "登陆已过期,请重新登陆"

**Comment by ywb21201** [comment]
我后端和前端是布署在不同的域名，是不是这样导致了session丢失了

**Comment by Heeexy** [comment]
sessionid没有带上   可以考虑配置跨域  或者带token做认证   具体做法搜一下哈
