### ISSUE TITLE
MyBatis resultMap映射

### ISSUE THREAD

**Issue by simonwangtx** [Heeexy/SpringBoot-Shiro-Vue#37]
![github-issue](https://user-images.githubusercontent.com/14939002/47350304-25d0d580-d6e8-11e8-98ed-1bca3a763ea0.jpg)

如图，这个One2Many的Model里并没有具体字段的定义，因此导致了Mybatis查询完数据后orm映射时出错。请问是我忽略了什么吗？

**Comment by Heeexy** [comment]
One2Many其实就是个HashMap 
查询出了什么错误呢

**Comment by simonwangtx** [comment]
如果直接在数据库里执行mybatis生成的sql，是正常的。因此应该是mybatis查询完毕之后，映射到OneToMany时出的错。Spring报错截图如下：
![github-issue](https://user-images.githubusercontent.com/14939002/47350864-62e99780-d6e9-11e8-911b-aa00b596c382.jpg)

**Comment by simonwangtx** [comment]
完整点的log:
![github-issue](https://user-images.githubusercontent.com/14939002/47351358-60d40880-d6ea-11e8-8246-dab9b290d252.jpg)

**Comment by simonwangtx** [comment]
找到问题了，我单步了一下，发现传入dao接口的参数是"USERNAME"不是"username"，所以mybatis读取参数的时候报错了。应该是和我用的oracle数据库有关系，所有数据库字段名称都自动大写了。
