### ISSUE TITLE
注解权限控制是否存在缺陷？

### ISSUE THREAD

**Issue by cliff01** [Heeexy/SpringBoot-Shiro-Vue#4]
在控制类里面通过泛型封装一层实现简单的增删改查，注解好像不能动态绑定。请问是否有其它思路？

**Comment by Heeexy** [comment]
不太明白。。能贴出代码么

**Comment by cliff01** [comment]
public abstract class BaseCRUDController<PK extends Serializable, M extends BaseModel<PK>, S extends BaseCRUDService<PK, M>> extends BaseController {
@RequestMapping(value="/edit",method = RequestMethod.POST)
	@ResponseStatus(HttpStatus.OK)
	@ApiOperation(value = "编辑对象", notes = "返回修改的条目数量")
	@ApiResponses(value = { @ApiResponse(code = 204, message = "编辑成功"), @ApiResponse(code = 400, message = "参数错误") })
	public Integer edit(@ApiParam(value = "编辑对象", required = true) @Valid @RequestBody M bean, Errors errors) {
		if (errors.hasErrors()) { throw new ParameterErrorException(errors.getFieldErrors()); }
		return service.edit(bean);
	}
}

**Comment by Heeexy** [comment]
@RequirePermissions() 注解无效么？

如果无效的话也可以试试 shiro 配置文件的方式

**Comment by cliff01** [comment]
我的控制类通过继承BaseCRUDController，注入不同的bean就可以实现对象的修改，而控制类里面不用写这个实现。注解在抽象类里面的话就不能对子类分开控制了。

**Comment by Heeexy** [comment]
@requirepermissions()肯定是需要写在每个具体的子类的每个方法上的，要不然就不算是具体的权限控制了。

**Comment by cliff01** [comment]
项目中采用rest会抽象一层对简单的增删改查做封装，shiro注解没有可以动态绑定变量，springmvc可以动态绑定，所以这里需要额外做个过滤器来实现了。
