### ISSUE TITLE
404

### ISSUE THREAD

**Issue by zhangzheming629** [Heeexy/SpringBoot-Shiro-Vue#40]
Request failed with status code 404

network中的提示
http://localhost:9520/api/login/auth

api.js中 import {getToken} from '@/utils/auth' 是灰色的
user.js中
import {getInfo, login, logout} from '@/api/login'
import {getToken, removeToken, setToken} from '@/utils/auth' 也是灰色的

**Comment by Heeexy** [comment]
灰色的没关系，idea的问题。
404的话检查下后端服务有没有这个接口
localhost:8080/login/auth
