### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by hustxay** [Heeexy/SpringBoot-Shiro-Vue#41]
建议增加后台功能，在后台增加菜单配置功能，而不是把所有的菜单都写到前端去，前端从后端数据库中返回菜单列表

**Comment by Heeexy** [comment]
的确，在前端写这么多配置很繁琐，搞不好和数据库不同步还容易出错。
不过前端除了菜单配置之外，还有很多按钮权限判断离不开权限数据。
要是有好的实现方法欢迎提出来哈
