### ISSUE TITLE
vue登录的问题

### ISSUE THREAD

**Issue by JohneySen** [Heeexy/SpringBoot-Shiro-Vue#48]
登录校验那个地方
if ("success" === data.result) {
       this.$router.push({path: '/'})
} else {
       this.$message.error("账号/密码错误");
 }为什么只有"success"才能跳转呢？
我改成
if ("true" === data.result) {
       this.$router.push({path: '/'})
} else {
       this.$message.error("账号/密码错误");
 }
后台json也是{"result":"true"}
就不行呢？

**Comment by Heeexy** [comment]
不应该啊   你把data里的信息都打出来看看呢

**Comment by JohneySen** [comment]
> 不应该啊 你把data里的信息都打出来看看呢

额原因是，store/modules/user.js  中也进行了返回值校验。。。

 Login({commit, state}, loginForm) {
      return new Promise((resolve, reject) => {
        api({
          url: "login/auth",
          method: "post",
          data: loginForm
        }).then(data => {
          if (data.result === "success") {
            //cookie中保存前端登录状态
            setToken();
          }
          resolve(data);
        }).catch(err => {
          reject(err)
        })
      })
    }
