### ISSUE TITLE
日志文件乱码

### ISSUE THREAD

**Issue by willxiang** [Heeexy/SpringBoot-Shiro-Vue#49]
`logback.xml`中27行和47行的
```xml
<charset>UTF-8</charset>
```
注释掉后日志打印就不出现乱码了……

**Comment by Heeexy** [comment]
我这个几个项目和环境都没遇到这个问题哈，在一些环境没加utf-8遇到了乱码，所以加上了

**Comment by willxiang** [comment]
> 我这个几个项目和环境都没遇到这个问题哈，在一些环境没加utf-8遇到了乱码，所以加上了

好的谢谢回复！可能是我自己电脑的问题
