### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by xiaosongdhls** [Heeexy/SpringBoot-Shiro-Vue#53]
这个怎么解决

**Comment by Heeexy** [comment]
请先使用未经修改的项目代码启动，debug排查，还有问题的话带上详细的描述

**Comment by xiaosongdhls** [comment]
我没有修改的 直接下载的源码

**Comment by Heeexy** [comment]
请求哪个接口404，直接请求localhost:8080的这个接口返回啥

**Comment by xiaosongdhls** [comment]
前端404 http://localhost:9520/#/login  http://localhost:8080/ 404

**Comment by Heeexy** [comment]
http://localhost:8080/ 404?   后端项目启动了么

**Comment by xiaosongdhls** [comment]
启动了
