### ISSUE TITLE
发现多标签页下，使用同一个用户会bug，已经提供修改

### ISSUE THREAD

**Issue by stone2317** [Heeexy/SpringBoot-Shiro-Vue#56]
问题描述：
1和2两个chrome标签页，使用admin登录.流程如下：1登录，点击文章.2登录，点击文章.1登出.2点击文章（因为cookie没了，回到登录界面），2登录，点击文章，报错，后台报没有permission.
核心原因是：permission.js中的store.getters.role和cookie的不一致.cookie是跨标签页共享的.1登出，2的cookie没了，2标签点击回到登录界面，再登录，但是role没有清除，使用没有调用store.dispatch('GetInfo'),从而后台没有报错没有权限.
问题已经修改
    //如果路径不是白名单内的,而且又没有登录,就跳转登录页面
    store.commit('RESET_USER')     permission.js中加上重置role即可
    next('/login')

**Comment by Heeexy** [comment]
感谢，已修改！
