### ISSUE TITLE
后台数据对象都是jsonObject，可读性不是很好

### ISSUE THREAD

**Issue by stone2317** [Heeexy/SpringBoot-Shiro-Vue#57]
虽然配合方便的mybatis数据库语句，关联关系都在sql中了，但是对象都是jsonobject，看到该对象，根本不知道里面有哪些字段，这是一种好的设计习惯么，还是说代码量少，快速搭建工程，复杂的还是应该有各种业务对象bean呢.

**Comment by Heeexy** [comment]
是的，jsonobject的确只是适合小项目，单人开发，多人开发或者长期维护的话还是要约定好bean啊
