### ISSUE TITLE
UserRealm实现是不是存在问题呀

### ISSUE THREAD

**Issue by zhouyangok** [Heeexy/SpringBoot-Shiro-Vue#59]
代码里面，登录的时候session里面只是存了Constants.SESSION_USER_INFO，但是在鉴权的时候却要在session中取到SESSION_USER_PERMISSION。

**Comment by Heeexy** [comment]
在 /login/getInfo接口中有权限信息，可以根据自己项目需求设计登录接口和查权限接口是否要分开
