### ISSUE TITLE
关于权限新解

### ISSUE THREAD

**Issue by zishinan** [Heeexy/SpringBoot-Shiro-Vue#6]
更好的办法是：角色-权限组-权限，一个角色对应多个权限组，一个权限组对应多个权限。

**Comment by Heeexy** [comment]
也可以那么做，那个其实就和一个人能选多种角色一样啦。
我一开始就是准备一个人选多种角色的，公司说太复杂用不着，就改掉了。
主要是看业务需求要不要那么复杂吧。
