### ISSUE TITLE
路由钩子

### ISSUE THREAD

**Issue by yesFighting** [Heeexy/SpringBoot-Shiro-Vue#60]
你好，我然后自己在按照你这个项目写，然后遇到了问题，在路由钩子里面 store.getters.role这一句的值是在什么时候做了变化的，我那里一直为false，进不去getinfo。能加个qq好友请教请教么

**Comment by Heeexy** [comment]
user.js  GetInfo方法里  commit('SET_USER', data.userPermission); 保存的用户信息的
qq不怎么用了，可以发邮件给我或者留个微信交流哈

**Comment by yesFighting** [comment]
问题解决了，我微信 aszx7538 有些数据还需要和大佬讨论一下

**Comment by yesFighting** [comment]
就是在路由钩子里面判断使用的是 ！store.getters.role 这样这里就一直为false，拿不到Getinfo的接口了
