### ISSUE TITLE
前端启动报错

### ISSUE THREAD

**Issue by util-you-com** [Heeexy/SpringBoot-Shiro-Vue#62]
![image](https://user-images.githubusercontent.com/49892690/61809616-4644e080-ae70-11e9-89bc-b6b9a150ba2a.png)
我用的是代理，所以没用 cnpm，但是应该不是这个问题吧

**Comment by Heeexy** [comment]
可能是npm版本太高了~  项目我好久没维护了  抱歉

**Comment by util-you-com** [comment]
？我还以为是版本太低了呢！

**Comment by util-you-com** [comment]
谢谢

**Comment by util-you-com** [comment]
我解决了，果然是 nodejs 版本太高了，降低为 10.15 版本就好了，谢谢大佬啊
