### ISSUE TITLE
你好,生产环境如何配置呢?一直登陆过期

### ISSUE THREAD

**Issue by hzhh110** [Heeexy/SpringBoot-Shiro-Vue#63]
module.exports = {
  NODE_ENV: '"production"',
  BASE_URL:'"/api"',
}

    server {
    listen       80;
    server_name  admin.juhui.com;

    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        root /Users/huangzhenhui/Desktop/巨晖项目/IoTVueAdmin/dist;
        index index.html index.htm;
    }
    location /api/ { 
         proxy_pass  http://127.0.0.1:8100;
         proxy_connect_timeout 600;
         proxy_read_timeout 600;
#        proxy_redirect  off;
#        proxy_set_header  Host $host;
#        proxy_set_header  X_Real_IP $remote_addr;
#        proxy_set_header  X_Forwarded_For $proxy_add_x_forwarded_for;
#        proxy_connect_timeout  150;
#        proxy_read_timeout  300;
#        proxy_send_timeout  300;
    }

**Comment by Heeexy** [comment]
看起来是cookie没有带过去，每个请求sessionId都变了 
搜一下nginx cookie 关键词呢 比如https://www.cnblogs.com/aligege/p/8126573.html

**Comment by hzhh110** [comment]
`server {
        listen       80;
        server_name  admin.juhui.com;

        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        location / {
            root /Users/huangzhenhui/Desktop/巨晖项目/IoTVueAdmin/dist;
            index index.html index.htm;
        }

        location /api{

          proxy_pass http://127.0.0.1/8100;

          proxy_cookie_path  /project /api;

        }
    }`


一直失败,也不知道怎么回事
