### ISSUE TITLE
直接放public就找不到路径了

### ISSUE THREAD

**Issue by hzhh110** [Heeexy/SpringBoot-Shiro-Vue#64]
![image](https://user-images.githubusercontent.com/19906209/63663509-3b75c680-c7f5-11e9-86d5-4ee13486fbda.png)
http://127.0.0.1:8100 {"msg":"请求路径不存在","code":"501","info":{}}

**Comment by Heeexy** [comment]
有个DefaultView.java文件

**Comment by hzhh110** [comment]
DefaultView.java
`@Configuration
public class DefaultView extends WebMvcConfigurerAdapter {
	@Override
	public void addViewControllers(ViewControllerRegistry registry) {
		registry.addViewController("/").setViewName("forward:/index.html");
		registry.setOrder(Ordered.HIGHEST_PRECEDENCE);
		super.addViewControllers(registry);
	}
}`

这个怎么修改呢?

**Comment by hzhh110** [comment]
{"msg":"请求路径不存在","code":"501","info":{}}

**Comment by Heeexy** [comment]
应该不用修改的。public目录下有index.html就可以了
