### ISSUE TITLE
好,需要帮忙,我发到服务器的时候,会出现Long类型不精准,用本地的运行,Long类型会String,没此问题

### ISSUE THREAD

**Issue by hzhh110** [Heeexy/SpringBoot-Shiro-Vue#67]
@Configuration
public class DefaultView extends WebMvcConfigurerAdapter {
    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        MappingJackson2HttpMessageConverter jackson2HttpMessageConverter = new MappingJackson2HttpMessageConverter();
        ObjectMapper objectMapper = new ObjectMapper();
        /**
         * 序列换成json时,将所有的long变成string
         * 因为js中得数字类型不能包含所有的java long值
         */
        SimpleModule simpleModule = new SimpleModule();
        simpleModule.addSerializer(Long.class, ToStringSerializer.instance);
        simpleModule.addSerializer(Long.TYPE, ToStringSerializer.instance);
        objectMapper.registerModule(simpleModule);
        jackson2HttpMessageConverter.setObjectMapper(objectMapper);
        converters.add(jackson2HttpMessageConverter);
    }
//    /**
//     * <p>Description: 解决js处理long型丢失精度问题，将long转换成long</p>
//     * @author hanchao
//     * @date 2018/7/23 下午4:31
//     */
//    @Override
//    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
//        //定义Json转换器
//        MappingJackson2HttpMessageConverter jackson2HttpMessageConverter =
//                new MappingJackson2HttpMessageConverter();
//        //定义对象映射器
//        ObjectMapper objectMapper = new ObjectMapper();
//        //定义对象模型
//        SimpleModule simpleModule = new SimpleModule();
//        //添加对长整型的转换关系
//        simpleModule.addSerializer(BigInteger.class, ToStringSerializer.instance);
//        simpleModule.addSerializer(Long.class, ToStringSerializer.instance);
//        simpleModule.addSerializer(Long.TYPE, ToStringSerializer.instance);
//        //将对象模型添加至对象映射器
//        objectMapper.registerModule(simpleModule);
//        //将对象映射器添加至Json转换器
//        jackson2HttpMessageConverter.setObjectMapper(objectMapper);
//
//        //在转换器列表中添加自定义的Json转换器
//        converters.add(jackson2HttpMessageConverter);
//        //添加utf-8的默认String转换器
//        converters.add(new StringHttpMessageConverter(Charset.forName("UTF-8")));
//    }
	@Override
	public void addViewControllers(ViewControllerRegistry registry) {
		registry.addViewController("/").setViewName("forward:/index.html");
//		registry.addViewController("/").setViewName("public/index.html");
		registry.setOrder(Ordered.HIGHEST_PRECEDENCE);
		super.addViewControllers(registry);
	}
}

**Comment by vae-Eason** [comment]
你前端怎么部署到服务器的，nginx嘛

**Comment by Heeexy** [comment]
> 你前端怎么部署到服务器的，nginx嘛

可以用nginx ，要研究下。  我图省事直接打包扔到后端文件夹里去了，一起发布，这样不太好

**Comment by vae-Eason** [comment]
我研究半天了，一直不行

**Comment by bennyrhys** [comment]
怎么搭建运行环境 写一下吧 idea还是eclpse 弄了半天缺文件吗

**Comment by gagazhang** [comment]
没有数据库文件

**Comment by LuckyCurve** [comment]
SQL文件运行报错，嗯呐嗯呐

**Comment by Heeexy** [comment]
> SQL文件运行报错，嗯呐嗯呐

不好意思很久没维护，近期找工作也没时间维护这个。

可能我当时的mysql版本比较老了。
具体问题你看看报的啥错，应该网上能搜到解决方案哈

**Comment by yangzelu** [comment]
大哥，你发错人了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Heeexy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月22日(星期六) 晚上6:02
收件人:&nbsp;"Heeexy/SpringBoot-Shiro-Vue"<SpringBoot-Shiro-Vue@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [Heeexy/SpringBoot-Shiro-Vue] 好,需要帮忙,我发到服务器的时候,会出现Long类型不精准,用本地的运行,Long类型会String,没此问题 (#67)



 
SQL文件运行报错，嗯呐嗯呐
  
不好意思很久没维护，近期找工作也没时间维护这个。
 
可能我当时的mysql版本比较老了。
 具体问题你看看报的啥错，应该网上能搜到解决方案哈

**Comment by LuckyCurve** [comment]
SQL文件运行报错，嗯呐嗯呐
  
不好意思很久没维护，近期找工作也没时间维护这个。
 
可能我当时的mysql版本比较老了。
 具体问题你看看报的啥错，应该网上能搜到解决方案哈




google了下，都说是符号的问题，可是改了几遍还是报错，

能帮忙看下吗，报错信息放在附件里面了

运行环境：mysql 8.0.17&nbsp; &nbsp;用navicat客户端运行sql文件
