### ISSUE TITLE
关于接口注解的问题

### ISSUE THREAD

**Issue by yeruilong** [Heeexy/SpringBoot-Shiro-Vue#74]
我发现接口上的注解，注释掉完全不影响功能，所以想问题这个注解是在哪用到的呢？代码里也没看到在哪针对接口上的注解做处理

**Comment by Heeexy** [comment]
具体哪个注解呢

**Comment by yeruilong** [comment]
就是@permission这个注解，不知道在哪会处理这个注解，所以想请教一下

**Comment by Heeexy** [comment]
等这几天有时间我回家看下哈，很久没看过代码了

**Comment by yeruilong** [comment]
没事哈，感谢答复，能否问下方便加个QQ啥的吗？后面有问题请教会方便一些^_^

**Comment by Heeexy** [comment]
发下你微信号到我邮箱哈

**Comment by yeruilong** [comment]
想问下你邮箱多少呢？

**Comment by yeruilong** [comment]
发过去了哈，有空查收一下^_^

**Comment by Heeexy** [comment]
> 就是@Permission这个注解，不知道在哪会处理这个注解，所以想请教一下

没找到@Permission这个注解啊

**Comment by Heeexy** [comment]
https://blog.csdn.net/u013995395/article/details/90718739   
@RequiresPermissions设计与 实现
