### ISSUE TITLE
前后端服务启动部署问题

### ISSUE THREAD

**Issue by yunwenlong** [Heeexy/SpringBoot-Shiro-Vue#79]
前端，在package.json里没有run dev,start等命令。
后端，不太清楚是怎么运行的，是将vue的代码打包之后放到java里面去跑，还是将前后端分开部署呢？

**Comment by Heeexy** [comment]
package.json第8、9行有

前端代码打包成静态文件后，可以在nginx中配置，与后端分开部署。
也可以放到java项目的静态资源文件夹里，一起部署
