### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by yunwenlong** [Heeexy/SpringBoot-Shiro-Vue#82]
1.目前已将vue打包放到springboot里面，并且运行起来，进入后台页面，但是，登录的时候提示账户密码不正确且不打印日志。将vue启动，进入页面，就可以成功登录并且打印日志。

**Comment by yunwenlong** [comment]
登录以及日志问题已经解决，目前就是vue和java分开部署的时候，有问题出现，能不能贴一下配置。

**Comment by Heeexy** [comment]
Nginx配置需要自己去查下哈， 我没配过
