### ISSUE TITLE
探讨

### ISSUE THREAD

**Issue by zhangshuaiGH** [Heeexy/SpringBoot-Shiro-Vue#85]
我看了您的系统，一个用户对应一个角色。您的思路非常好可以适用于大多数情况，但是我在实际的项目中，会遇到角色-权限的整体变更，比如一个新增模块后，同一角色中的用户群对应新增模块权限不同，就需要整体变更角色的权限，再重新赋予用户角色，不便于增加模块和减少模块。不成熟的想法。

**Comment by Heeexy** [comment]
可以做一个用户对应多个角色的，稍微改动下代码。

特殊的模块单独建个角色，给部分用户添加这个角色就行
