### ISSUE TITLE
跨域sessionid问题

### ISSUE THREAD

**Issue by JasonLu0117** [Heeexy/SpringBoot-Shiro-Vue#9]
请问一下，为什么你的前端没有加withCredentials: true，但是每次请求的sessionid还是一致的？

**Comment by Heeexy** [comment]
因为设置了 config/index.js中设置了 proxyTable ，等于开发环境用了node的代理吧。

**Comment by JasonLu0117** [comment]
但是我自己的项目中也设置了proxyTable，然后后端也按照你的这个项目中实现，可是每次请求过来的sessionid都不一致

**Comment by JasonLu0117** [comment]
哦，找到问题了，是proxyTable的配置的path要和后端的根目录一致
