### ISSUE TITLE
登录问题，登录成功自动调用login,还拼接了jessionid,导致退回登录部分浏览器没这问题

### ISSUE THREAD

**Issue by akido-alert** [Heeexy/SpringBoot-Shiro-Vue#93]
![image](https://user-images.githubusercontent.com/36099881/91534794-be6bb880-e944-11ea-851b-421e18dcb295.png)
之前用的谷歌浏览器，然后过了段时间就出这个问题了，其他浏览器好像没有这个问题

**Comment by Heeexy** [comment]
没看明白，这是啥，这个项目本身也没有login接口啊
