### ISSUE TITLE
打包无法使用

### ISSUE THREAD

**Issue by xuuuxg** [Heeexy/SpringBoot-Shiro-Vue#96]
npm run build打包以后无法使用，请问您有解决或者我哪里配置错误了？

**Comment by Heeexy** [comment]
【无法使用】具体是什么现象？

**Comment by xuuuxg** [comment]
打包跨域请求两次，一次options，一次post，认证得时候会失败。。。。
![image](https://user-images.githubusercontent.com/18170543/96426816-52b11800-1230-11eb-820c-cc041269ccfa.png)

**Comment by Heeexy** [comment]
打包后的静态文件是放到哪里的？
看起来是放在后端静态文件夹的，怎么还会跨域？ 可以截图F12的network部分看看。

20011是后端接口返回的么

**Comment by xuuuxg** [comment]
对的，是后端返回的。
我是打包后部署在apache tomcat内了
断点直接进入到下图方法内
![image](https://user-images.githubusercontent.com/18170543/96449004-ca8a3d00-1246-11eb-9b16-79594035c119.png)

**Comment by Heeexy** [comment]
打包后直接放到后端的 src/main/resources/static 目录下面就可以了。
