### ISSUE TITLE
vue部分  npm  install 报错

### ISSUE THREAD

**Issue by 1yfgT53** [Heeexy/SpringBoot-Shiro-Vue#98]
vue部分  npm  install 报错
npm ERR! Maximum call stack size exceeded
完整日志
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN vue-admin@3.1.0 No description
npm WARN vue-admin@3.1.0 No repository field.

npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:

**Comment by Heeexy** [comment]
1.删了node_modules
2.用--registry=https://registry.npm.taobao.org
3.用cnpm
4.换node版本

4种方法都试试哈，不清楚哪个好使
