### ISSUE TITLE
前端依赖的node版本是多少，在node10、node14下npm install 都报错了

### ISSUE THREAD

**Issue by ufoe** [Heeexy/SpringBoot-Shiro-Vue#99]
前端依赖的node版本是多少，在node10、node14下npm install 都报错了

**Comment by Heeexy** [comment]
刚使用 v14.12.0是好使的， mac下的报错没什么影响
另外4种方法：
1.删了node_modules
2.用--registry=https://registry.npm.taobao.org
3.用cnpm
4.换node版本

4种方法都试试哈，不清楚哪个好使

**Comment by ufoe** [comment]
删了依赖，重新install 好了

**Comment by godwinnnnn** [comment]
先删除了 node_modeles
npm install --registry=https://registry.npm.taobao.org/
